server:
  host: ""
  port: 

venue:
  location: ""
  timezone: ""
  integration_start_date: ""

zl:
  api_base_url: "https://api.zerolatencyvr.com/api/v1"
  site_id: 

roller:
  api_base_url: "https://api.roller.app"

email:
  admin_email: ""
  info_email: ""
  dev_email: ""

vr_packages:
  - package_name: ""
    roller_ids: []
    zl_id: 

other_packages:
  - package_name: ""
    roller_ids: []
    zl_id: 