server:
  host: ""
  port: 

venue:
  location: ""
  timezone: ""
  integration_start_date: "2024-06-01T00:00:00"
  attractions:
    - name: "ZLVR"
      gamespace: 123
    - name: ""
      gamespace: 

zl:
  api_base_url: "https://api.zerolatencyvr.com/api/v1"
  site_id: 

roller:
  api_base_url: "https://api.roller.app"

email:
  admin_email: ""
  info_email: ""
  dev_email: ""

vr_packages:
  - package_name: ""
    roller_ids: []
    zl_id: 
    private: false

other_packages:
  - package_name: ""
    roller_ids: []
    zl_id: 
    attraction: ""
    private: false